// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryModalController from "./category_modal_controller"
application.register("category-modal", CategoryModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import RecipetItemsController from "./recipet_items_controller"
application.register("recipet-items", RecipetItemsController)
